Added anchor links
dotnet/AspNetDocs pull request #501
Opened 2021-03-02 16:24 UTC by KalleHoppe

Added anchor links to the sections in the checklist

2021-03-02 16:24 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/AspNetDocs?pullRequest=501) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetDocs?pullRequest=501) before we can accept your contribution.<br/><br/>:x: KalleHoppe [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetDocs?pullRequest=501)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetDocs?pullRequest=501) it.</sub>

2021-03-03 19:59 UTC, Rick-Anderson requested changes
Change all to lower case

2021-03-03 19:59 UTC, Rick-Anderson commented on aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application.md
> +> * [Create an MVC web app](#Create-an-MVC-web-app)
Tag names in XHTML are case sensitive.  You need to make all the letters lower case.

2021-03-03 20:00 UTC, closed without merging

2021-03-03 20:04 UTC, Rick-Anderson commented
@KalleHoppe  thanks for the thought though. I'm sure you can find docs to improve.