[BrokenLinksH2]
dotnet/AspNetDocs pull request #611
Opened 2022-04-06 15:36 UTC by DhurataJ

Fixing broken links in which were related to AsptNetDocs:

Files: 
- https://docs.microsoft.com/en-us/aspnet/identity/overview/extensibility/implementing-a-custom-mysql-aspnet-identity-storage-provider
- https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/account-confirmation-and-password-recovery-with-aspnet-identity
- https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/two-factor-authentication-using-sms-and-email-with-aspnet-identity
- https://docs.microsoft.com/en-us/aspnet/identity/overview/getting-started/aspnet-identity-recommended-resources
- https://docs.microsoft.com/en-us/aspnet/identity/overview/getting-started/aspnet-identity-using-mysql-storage-with-an-entityframework-mysql-provider
- https://docs.microsoft.com/en-us/aspnet/identity/overview/getting-started/developing-aspnet-apps-with-windows-azure-active-directory

2022-04-06 15:36 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/AspNetDocs?pullRequest=611) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetDocs?pullRequest=611) before we can accept your contribution.<br/><br/>:x: DhurataJ [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetDocs?pullRequest=611)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetDocs?pullRequest=611) it.</sub>

2022-04-07 18:50 UTC, DhurataJ commented
**Global effort to fix broken links**

@Rick-Anderson 

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

2022-04-07 18:55 UTC, Rick-Anderson requested changes
remove en-us/

2022-04-07 18:55 UTC, Rick-Anderson commented on aspnet/mvc/overview/deployment/docker-aspnetmvc.md
> +> If you are using Windows Server 2016, follow the instructions for [Container Host Deployment - Windows Server](https://docs.microsoft.com/en-us/virtualization/windowscontainers/).
```suggestion
> If you are using Windows Server 2016, follow the instructions for [Container Host Deployment - Windows Server](https://docs.microsoft.com/virtualization/windowscontainers/).
```

2022-04-07 18:55 UTC, Rick-Anderson commented on aspnet/mvc/overview/getting-started/introduction/adding-search.md
> +The code uses the `AddRange` method of the generic `List` collection to add all the distinct genres to the list. (Without the `Distinct` modifier, duplicate genres would be added — for example, comed
remove all language , that is, /en-us from URLs

2022-04-07 20:34 UTC, Rick-Anderson approved these changes

2022-04-07 20:34 UTC, merged

2022-05-05 14:19 UTC, TheMythoclast commented on aspnet/visual-studio/overview/2013/aspnet-and-web-tools-20132-preview-for-visual-studio-2013-release-notes.md
> +There were lots of bugs that were fixed in this release.
I will attempt to find some patch notes. There were a lot of bugs that were fixed in this release.