Validation: May 6th. Fixed Alt-text and Invalid-author
dotnet/AspNetDocs pull request #638
Opened 2022-05-06 15:25 UTC by Angelines-YG

Fixed several alt-text missing issues and invalid-author

2022-05-06 15:25 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/AspNetDocs?pullRequest=638) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetDocs?pullRequest=638) before we can accept your contribution.<br/><br/>:x: Angelines-YG [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetDocs?pullRequest=638)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetDocs?pullRequest=638) it.</sub>

2022-05-06 15:45 UTC, kturetz commented on aspnet/aspnet/overview/owin-and-katana/getting-started-with-owin-and-katana.md
> +![Installing Package Manger, example illustration](getting-started-with-owin-and-katana/_static/image3.png)
Should that be "Package Manager"?

2022-05-06 15:46 UTC, kturetz commented on aspnet/aspnet/overview/owin-and-katana/getting-started-with-owin-and-katana.md
> +![Randome exeption image example](getting-started-with-owin-and-katana/_static/image7.png)
Should that be "Random"?

2022-05-06 15:48 UTC, kturetz commented on aspnet/aspnet/overview/owin-and-katana/host-owin-in-an-azure-worker-role.md
"Sign-in"?

2022-05-06 15:54 UTC, Angelines-YG commented
@Rick-Anderson 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge

2022-05-06 19:06 UTC, Rick-Anderson requested changes

2022-05-06 19:06 UTC, Rick-Anderson commented on aspnet/aspnet/overview/owin-and-katana/enabling-windows-authentication-in-katana.md
> +author: StephenBrentPeters
```suggestion
author: rick-anderson
```

2022-05-06 19:06 UTC, Rick-Anderson commented on aspnet/aspnet/overview/owin-and-katana/getting-started-with-owin-and-katana.md
> +author: StephenBrentPeters
fix as previous

2022-05-06 19:06 UTC, Rick-Anderson commented on aspnet/aspnet/overview/owin-and-katana/host-owin-in-an-azure-worker-role.md
> +author: StephenBrentPeters
fix

2022-05-10 01:37 UTC, Angelines-YG commented
@Rick-Anderson 

Requested changes have been made. 
Please review within five business days and merge or comment in the PR with any additional changes you’d like to see. Thank you!

2022-05-10 01:39 UTC, Rick-Anderson approved these changes

2022-05-10 01:40 UTC, merged