[BrokenLinksH2] fixing broken links
dotnet/AspNetDocs pull request #692
Opened 2022-05-25 00:34 UTC by StephenBrentPeters

**Global effort to fix broken links**

@Rick-Anderson 

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

2022-05-26 23:57 UTC, Rick-Anderson requested changes

2022-05-26 23:57 UTC, Rick-Anderson commented on aspnet/web-forms/overview/older-versions-getting-started/aspnet-ajax/understanding-asp-net-ajax-debugging-capabilities.md
> +ms.date: 03/28/2008s
fix

2022-05-27 17:06 UTC, StephenBrentPeters commented
#sign-off

2022-05-27 22:02 UTC, Rick-Anderson approved these changes

2022-05-27 22:02 UTC, merged