[Bulk]MS-10-13-AspNetDocs-fixes
dotnet/AspNetDocs pull request #790
Opened 2022-10-13 21:51 UTC by Roudabeh1348

2022-10-13 21:57 UTC, Roudabeh1348 commented
@Rick-Anderson The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues.
This PR includes only link fixes and does not change other content. I’d very much appreciate your timely review and feedback on the link changes I’ve suggested.

Thank you!

2022-10-13 23:06 UTC, Rick-Anderson requested changes

2022-10-13 23:06 UTC, Rick-Anderson commented on aspnet/web-pages/overview/mobile/rendering-aspnet-web-pages-sites-for-mobile-devices.md
> +> To test mobile pages, you can use a mobile device simulator that runs on a desktop computer. This tool lets you test web pages as they would look on mobile devices (that is, typically with a much s
```suggestion
> To test mobile pages, you can use a mobile device simulator that runs on a desktop computer. This tool lets you test web pages as they would look on mobile devices (that is, typically with a much smaller display area). One example of a simulator is the [User Agent Switcher add-on](https://addons.mozilla.org/firefox/addon/uaswitcher/) for Mozilla Firefox, which lets you emulate various mobile browsers from a desktop version of Firefox.
```

2022-10-13 23:06 UTC, Rick-Anderson commented on aspnet/web-pages/overview/releases/top-features-in-web-pages-2.md
> +    > To test mobile pages, you can use a mobile device simulator that runs on a desktop computer. This tool lets you test web pages as they would look on mobile devices (that is, typically with a mu
same as previous, remove `/en-US`

2022-10-13 23:15 UTC, Roudabeh1348 commented on aspnet/web-pages/overview/releases/top-features-in-web-pages-2.md
> +    > To test mobile pages, you can use a mobile device simulator that runs on a desktop computer. This tool lets you test web pages as they would look on mobile devices (that is, typically with a mu
Removed the locale. :)

2022-10-13 23:15 UTC, Roudabeh1348 commented on aspnet/web-pages/overview/mobile/rendering-aspnet-web-pages-sites-for-mobile-devices.md
> +> To test mobile pages, you can use a mobile device simulator that runs on a desktop computer. This tool lets you test web pages as they would look on mobile devices (that is, typically with a much s
Removed the locale.

2022-10-14 00:04 UTC, Rick-Anderson approved these changes

2022-10-14 00:04 UTC, merged