Policheck update July 3 - couple of "countries" to "countries/regions" and correct typo counties/countries - Bulk update
dotnet/AspNetDocs pull request #851
Opened 2023-07-03 19:29 UTC by v-thepet

Fixes
https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/119670/?triage=true
https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/119589/?triage=true

2023-07-03 19:33 UTC, v-thepet commented
#sign-off

2023-07-28 00:14 UTC, Rick-Anderson requested changes
`countries/regions` doesn't MT (machine translate) and it's not correct English. We prefer `countries and regions" or something similar.

2023-07-31 17:29 UTC, v-thepet commented
#sign-off

2023-07-31 18:37 UTC, Rick-Anderson approved these changes

2023-07-31 18:37 UTC, merged