Q&M: Fix broken links identified by the Broken links report - fix 20 files
dotnet/AspNetDocs pull request #919
Opened 2024-11-05 23:47 UTC by Daidihuang

2024-11-06 23:38 UTC, Rick-Anderson requested changes
You can't just delete bad links, you need to delete the text too.

2024-11-06 23:38 UTC, Rick-Anderson commented on aspnet/ajax/cdn/overview.md
> +> Use this GitHub issue to report problems with the Microsoft Ajax CDN.
```suggestion
> Use [this GitHub issue](https://github.com/dotnet/AspNetCore.Docs/issues/34049) to report problems with the Microsoft Ajax CDN.
```

2024-11-06 23:38 UTC, Rick-Anderson commented on aspnet/mvc/overview/getting-started/database-first-development/generating-views.md
> +* When using Visual Studio 2022, install **Net Framework project and item templates**. For more information, see this GitHub issue.
```suggestion
* When using Visual Studio 2022, install **Net Framework project and item templates**. 
```

2024-11-06 23:38 UTC, Rick-Anderson commented on aspnet/web-forms/overview/older-versions-getting-started/master-pages/specifying-the-master-page-programmatically-cs.md
> +- ASP.NET Page Lifecycle Diagram
```suggestion
```

2024-11-06 23:38 UTC, Rick-Anderson commented on aspnet/web-forms/overview/older-versions-getting-started/master-pages/specifying-the-master-page-programmatically-vb.md
> +- ASP.NET Page Lifecycle Diagram
```suggestion
```

2024-11-07 19:05 UTC, Daidihuang commented
> You can't just delete bad links, you need to delete the text too.

Got it, thanks for informing,

2024-11-07 22:25 UTC, Rick-Anderson approved these changes

2024-11-07 22:25 UTC, merged